### PR TITLE
Fix: CodeCov's omitted files show up in report

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description
CodeCov's omitted files partially show (e.g. files in `kissim/tests`  and `kissim._version.py`). Find out why and exclude them.

## Todos
  - [x] Test: Explicitly omit file that shows up in CodeCov but shouldn't (use as example `kissim/tests/conftest.py`). > no success
  - [x] Test: Add `--cov-config=setup.cfg` to `pytest` command in `.github/workflows/CI.yaml` > no success
  - [ ] Test: Pin `pytest` to version `5.*`

## Questions
Todos are in this case my questions :)

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Hopefully fixes #43

**Comment by dominiquesydow** [comment]
The following files should be omitted as defined in `setup.cfg`:
https://github.com/volkamerlab/kissim/blob/cf404b6585b83e5ef468481d2152809acaf2124d/setup.cfg#L5-L9

But the following files show up in the CodeCov report:
image
https://codecov.io/gh/volkamerlab/kissim/tree/7bf58aafc71aedc733310a1e00a1cc9e2a53bdd9/kissim

Observations:
- In `kissim/tests` interestingly only the files are included (not the subfolders).
- Also, interestingly, with this commit _all_ lines in `kissim._version.py` are included, before at least some lines were excluded. Such a behaviour has happened before, see here: https://github.com/volkamerlab/kissim/pull/42#issuecomment-804130445

**Comment by dominiquesydow** [comment]
Try this suggestion by @j-wags (add `--cov-config=setup.cfg` to `pytest` command in `.github/workflows/CI.yaml`): https://github.com/MolSSI/cookiecutter-cms/issues/91

**Comment by dominiquesydow** [comment]
Lastest commit not analyzed by CodeCov
image

**Comment by dominiquesydow** [comment]
Latest CodeCov report: https://codecov.io/gh/volkamerlab/kissim/tree/10024c2bb65a90e1a9d09d6c6f81a4d0822aacac/kissim

**Comment by dominiquesydow** [comment]
Dropping this here - CI uses
```
pytest                    6.2.2            py37hf985489_0    conda-forge
pytest-cov                2.11.1             pyh44b312d_0    conda-forge
```

**Comment by dominiquesydow** [comment]
Compared this repo to another repo where the same `setup.cfg` and `CI.yaml` (w.r.t. to the `pytest` commands) files are used:
https://github.com/dominiquesydow/dynophores

There we use:
```
pytest                    5.4.3            py37hc8dfbb8_0    conda-forge
pytest-cov                2.11.1             pyh44b312d_0    conda-forge
```

`pytest` is pinned to version `5.*`
https://github.com/dominiquesydow/dynophores/blob/07e8747394010556c076f42eb68e65e729d31cf8/devtools/conda-envs/test_env.yaml#L21

Try that out.

**Comment by dominiquesydow** [comment]
The `kissim/tests` folder is omitted:
https://codecov.io/gh/volkamerlab/kissim/tree/e6ee7bbfa9bacffdadd16b49e7ff57530a2cffaf/kissim

`kissim/_version.py` is still there.

I am confused.

**Comment by dominiquesydow** [comment]
@jaimergp could you take a look at this PR - do you have any more pointers for me?

**Comment by jaimergp** [comment]
Can you try using your codecov.yml file instead? https://docs.codecov.io/docs/ignoring-paths

**Comment by dominiquesydow** [comment]
A bit embarressed to admit but I only just now understood that I am dealing with a truly two-step procedure here:

1. Generate `coverage.xml` file with `coverage.py`
    https://github.com/volkamerlab/kissim/blob/91923ac5f9db1b133ff5a918860c559965c5aed4/.github/workflows/CI.yaml#L54-L58
2. Upload the `coverage.xml` file to CodeCov 
   https://github.com/volkamerlab/kissim/blob/91923ac5f9db1b133ff5a918860c559965c5aed4/.github/workflows/CI.yaml#L59-L64
   - https://github.com/codecov/codecov-action
   - > When using pytest, use https://pypi.org/project/pytest-cov/ with the XML report. This report output is detected and uploaded by the Codecov upload script. https://docs.codecov.io/docs/python

---

That tells me finding the problem should not start with step 2 (CodeCov) but __step 1__. 

So I ran locally
`pytest -v --cov=kissim --cov-config=setup.cfg kissim/tests/`

and figured out that I have to adjust `kissim/_version.py` to `*/_version.py`
https://github.com/volkamerlab/kissim/blob/91923ac5f9db1b133ff5a918860c559965c5aed4/.github/workflows/CI.yaml#L54-L58

so that the coverage looks correct locally (no `kissim/_version.py`, nothing from `kissim/tests/`):
```
----------- coverage: platform linux, python 3.8.6-final-0 -----------
Name                                                  Stmts   Miss  Cover
-------------------------------------------------------------------------
kissim/__init__.py                                        5      0   100%
kissim/api/__init__.py                                    2      0   100%
kissim/api/compare.py                                    27      0   100%
kissim/api/encode.py                                     16      0   100%
kissim/cli/__init__.py                                    2      0   100%
kissim/cli/compare.py                                     8      0   100%
kissim/cli/encode.py                                     15      0   100%
kissim/cli/main.py                                       19      0   100%
kissim/cli/utils.py                                      17      0   100%
kissim/comparison/__init__.py                             4      0   100%
kissim/comparison/feature_distances.py                   76      0   100%
kissim/comparison/feature_distances_generator.py         94      0   100%
kissim/comparison/fingerprint_distance.py                39      1    97%
kissim/comparison/fingerprint_distance_generator.py     139      7    95%
kissim/comparison/utils.py                               26      0   100%
kissim/definitions.py                                    10      0   100%
kissim/encoding/__init__.py                               4      0   100%
kissim/encoding/base.py                                  73      0   100%
kissim/encoding/features/__init__.py                      5      0   100%
kissim/encoding/features/base.py                         17      0   100%
kissim/encoding/features/exposure.py                     70      1    99%
kissim/encoding/features/sco.py                          54      0   100%
kissim/encoding/features/sitealign.py                    54      0   100%
kissim/encoding/features/subpockets.py                   92      0   100%
kissim/encoding/fingerprint.py                           50      0   100%
kissim/encoding/fingerprint_generator.py                113      1    99%
kissim/encoding/fingerprint_normalized.py                57      0   100%
kissim/io/__init__.py                                     3      0   100%
kissim/io/biopython.py                                  179      8    96%
kissim/io/data.py                                        74      1    99%
kissim/io/dataframe.py                                   10      0   100%
kissim/schema.py                                          7      0   100%
kissim/utils.py                                          27      0   100%
-------------------------------------------------------------------------
TOTAL                                                  1388     19    99%
```

Next is __step 2__ - does CodeCov show the same? Waiting for the CI.

**Comment by dominiquesydow** [comment]
CodeCov for last commit:
https://codecov.io/gh/volkamerlab/kissim/tree/91923ac5f9db1b133ff5a918860c559965c5aed4/kissim

`kissim/_version.py` and `kissim/tests/*` are gone! :)

Differences from local coverage:
- `cli` module: 100% coverage locally, with GHA 19 missing lines - full [`main.py`](https://codecov.io/gh/volkamerlab/kissim/src/91923ac5f9db1b133ff5a918860c559965c5aed4/kissim/cli/main.py), means that subprocesses do not work?
- `utils` module: 100% coverage locally, with GHA 2 lines missing - no sure why yet, see [`utils.py` report](https://codecov.io/gh/volkamerlab/kissim/src/91923ac5f9db1b133ff5a918860c559965c5aed4/kissim/utils.py)

**Comment by dominiquesydow** [comment]
Merging this PR, since problem resolved. Attend to coverage improvements elsewhere.

**Pull request merged**
