### PR TITLE
Add 3D fingerprint view

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description
Use `nglview` to map fingerprint onto the 3D binding site. Use `ipywidgets` to change between features (e.g. exposure, size, distances to hinge region).

Desired functionalities:
| Number of objects | Aim | Action | Class name |
| -- | -- | -- | -- |
| 1 structure | Visualize fingerprint | Per feature, plot feature values onto pocket residues | `StructureViewer` |
| 1 kinase with &ge; 1 structures | Visualize fingerprint variability per kinase | Per feature, plot feature values std. of multiple structures | `KinaseViewer` |
| 2 structure | Visualize the difference between two fingerprints | Per feature, plot per-residue difference; use divergent colormap | `StructurePairViewer` |

## Todos
  - [x] Start with existing code in ["Example fingerprint in 3D"](https://nbviewer.jupyter.org/github/volkamerlab/kissim_app/blob/master/notebooks/fingerprints/feature_distribution_per_residue.ipynb) 
    - [x] Map one feature on one structure
    - [x] Add widget that allows us to toggle between features (to check if this even works in combo with `nglview`)
  - [x] Add `kissim.viewer.base._BaseViewer` class that will be used as parent class for all viewer applications
  - [x] Offer visualization with side chains (color on side chain) or without side chains (color on backbone)
  - [x] Add `kissim.viewer.structure.StructureViewer` to map fingerprint onto pocket (use `ipywidgets` to change feature types)
  - [x] Add `kissim.viewer.kinase.KinaseViewer` to map fingerprint variability onto pocket (use `ipywidgets` to change feature types)
    - [x] If std is 0: Colorbar is incorrect
    - [x] ~Use additional measures (besides std)?~ Not now.
  - [x] Add `kissim.viewer.pair.StructurePairViewer` to map fingerprint difference onto pocket (use `ipywidgets` to change feature types)
    - [x] Now we need a divergent colormap instead of viridis!
  - [x] Add log messages to output? (Use print statements; those will show up regardless of notebook logging settings)
  - [x] For distances and exposure, do not show side chains by default - since these features are only based on CA.
  - [x] Add unit tests

## Questions
- [x] What did we mean by "Optionally: For multiple objects: Show merged distance per residue (merge all features for one residue into a value)" > Leave this for a new PR when clarified

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Failing Windows CI `ValueError: stat: path too long for Windows ` should be fixed here: https://github.com/nglviewer/nglview/pull/977 (new release has not been cut, yet).

**Comment by hainm** [comment]
> ValueError: stat: path too long for Windows 

Why do you need to pass the long and unrealistic path to `nglview`?

**Comment by dominiquesydow** [comment]
> Why do you need to pass the long and unrealistic path to nglview?

Hi @hainm, 

Thanks for checking in!

I am using `add_component` to pass the PDB file content as a string:
https://github.com/volkamerlab/kissim/blob/e23d4f602f01724bc1a8e2e07dacbc3acbd0a3d8/kissim/viewer/base.py#L133

Under Windows, this string is treated as file path and therefore throws an error:
https://github.com/volkamerlab/kissim/runs/2785897927#step:6:552

I am using the _string_ instead of the _file_ because I fetch structural data remotely from the [KLIFS](https://klifs.net/) database and do not want to save files locally.

**Comment by hainm** [comment]
@dominiquesydow You can try this:
```
c = nglview.TextStructure(your_text)
view.add_component(c)
```

https://github.com/nglviewer/nglview/blob/4bab5accedc9131b6f58dbf11b887ee2b323416a/nglview/adaptor.py#L86

I don't know why `nglview` allow below because it's not the design. 
```
view.add_component(self._text, ext="pdb") 
```

**Comment by dominiquesydow** [comment]
@hainm, thank you, this seems to work nicely and looks much better than my version!

**Pull request merged**
